### PR TITLE
Upgrading loader utils to fix deprecation warning

### PR DESCRIPTION
**Pull request by randak**

### CODE REVIEW

**Comment by randak** [comment]
@d3viant0ne I'm sure you're busy, but is there any chance that you could take a look at this soon? It's a small PR and it will get this project onto the latest loader-utils. Thanks in advance!

**Comment by le0m** [comment]
any update on this?
(cross-reference: https://github.com/webpack-contrib/svg-inline-loader/pull/57)

**Comment by d3viant0ne** [comment]
@randak - Yeah, super slammed. The loader utils update requires a major version bump, as I said in the other PR, i'll try to get a Major version beta out that handles this + Webpack 4 support out by the end of the week.

**Comment by randak** [comment]
@d3viant0ne Thanks so much! Appreciate you getting back to me on this. Looking forward to not seeing that warning anymore :)

**Comment by le0m** [comment]
@d3viant0ne thanks for your time on this :)

**Pull request merged**
